### DISCUSSION TITLE
Restrictions on valid characters ldflags

### DISCUSSION THREAD

**Discussion by jimmyhmiller** [cabinpkg/cabin#1170] [General]
I'm trying to build things with cabin on macOS. I need to pass flags like `-framework Metal` for ldflags. When I try this I get errors no matter what format I try

```toml
ldflags = ["-framework", "Metal"] # flags but start with -
ldflags = ["-framework Metal"] # invalid character in flags (paraphrase)
```

When I remove these restrictions, the flags work fine and my build succeeds. Am I missing something I should be doing instead or are the checks overly restrictive?
