### DISCUSSION TITLE
Poac package build C++ standard

### DISCUSSION THREAD

**Discussion by oraqlle** [cabinpkg/cabin#647] [Q&A] [answered]
Does poac build packages against the standard specified for the package which can be sperate for the project building them (similar to Cargo) or are they all built using the current projects specified standard?

**Comment by ken-matsui** [comment, marked as answer]
This is also not implemented, but I plan to implement the following.

1. A dependency which is a build-required package (provides libraries) will be built using the package's standard (not the current project's standard).
2. A dependency which is a header-only package will be built using the current project's standard.

Case `1` is similar to Cargo, but `2` is not.
If the current project's standard (the `edition` key) is older than the header-only dependencies' standards, then Poac will emit an error.
However, since `edition` which is implicitly the minimum required version is confusing, it might be better to be able to specify a supported standard range like dependencies:

```toml
[package]
edition = ">=2011 and <2020" # This package uses `std::return_temporary_buffer` which was removed since C++20
```
