### DISCUSSION TITLE
Multi library setup

### DISCUSSION THREAD

**Discussion by oraqlle** [cabinpkg/cabin#648] [Q&A] [answered]
How do you specify a package with multiple libraries and how would a downstream user indicate the usage of these libraries?

**Comment by ken-matsui** [comment, marked as answer]
It is not implemented yet, but the ideal implementation would be the like following.

Just like [`features` of Cargo](https://doc.rust-lang.org/cargo/reference/features.html), `[libraries]` would provide `default` and `option`.

`Dep/poac.toml`

```toml
[libraries]
default = ["default1", "default2"]
option = ["option1", "option2"]
```

Then users specify libraries as long as users want to link.

`Package/poac.toml`

```toml
[dependencies]
Dep = "0.1.0" # "default1", "default2"
Dep = { version = "0.1.0", libraries = ["option1", "option2"] } # "default1", "default2", "option1", "option2"
Dep = { version = "0.1.0", default-libraries = false } # no lib will be linked
```
