### DISCUSSION TITLE
Specify Compiler Version

### DISCUSSION THREAD

**Discussion by oraqlle** [cabinpkg/cabin#758] [Q&A] [answered]
Is there a way to specify a particular version of a compiler to use in the `poac.toml`?

**Comment by ken-matsui** [comment, marked as answer]
@oraqlle No since we can specify the C++ version in [`edition`](https://github.com/poac-dev/poac/blob/dd9d13f594a1069ac4c034dc85b047758d276c9c/poac.toml#L4). Poac automatically detects whether or not your compiler supports the specified edition. If your edition is 2020 but your GCC is 7, then the compilation fails. The logic is here:

https://github.com/poac-dev/poac/blob/dd9d13f594a1069ac4c034dc85b047758d276c9c/lib/core/builder/compiler/cxx/gcc.cc#L76-L86

**Reply by oraqlle** [reply]
@ken-matsui, might be worth adding this an option in the future, Maybe even in the target configuration sections eg.

```toml
[target.'cfg(compiler = gcc)'.profile]
compiler-version = 13.1
```
Note this may be impossible in TOML the exact way I've described it but as an option. Alternatively, there could be a list of different compiler names as follows:

```toml
compilers = ["gcc", "clang", "gcc-13"]
default-compiler = "gcc"
```

Where they are just passed directly as command names and a default option can be given and other compilers can be chosen at the command line (`poac run -c gcc-13`). It might be interesting to see what Cargo is doing to enable multiple compilers as GCC's Rust compiler is being built.
