### DISCUSSION TITLE
tasks in poac.toml

### DISCUSSION THREAD

**Discussion by Heus-Sueh** [cabinpkg/cabin#983] [Ideas]
Something similar to python's taskipy: 

```toml
[tool.taskipy.tasks] 
test = "python -m unittest tests/test_*.py" 
lint = "pylint tests taskipy" 
```

Would this be within the scope of the project or is it better to use other tools that do this in general?
