### ISSUE TITLE
How to specify -stdlib when using clang++

### ISSUE THREAD

**Issue by watiko** [cabinpkg/cabin#923]
It is possible to specify `-stdlib` by writing the following in poac.toml, but it will not work when `CXX=g++`.

```toml
[profile]
cxxflags = ["-stdlib=libc++"]
```

I felt it would be useful if there was a way to make it work for both `CXX=clang++` and `CXX=g++`. I'm not sure what the best way is, but I wrote notes of what I came up with.
- Add `CXXFLAGS` environment variable (similar to `RUSTFLAGS`)
- Allow CXX to be fixed in poac.toml (profile.cxx?) to avoid confusion if only one cxx is assumed.

**Comment by ken-matsui** [comment]
@watiko  For conditional CXXFLAGS, I think adding `cfg` works better.  For example:

```toml
[target.'cfg(compiler = "clang++")'.profile]
cxxflags = ["-stdlib=libc++"]
```

For fixing CXX to a specific compiler, I am not sure that we should do it.  Let me think of it.
